USE relat_dinamico;

CREATE TABLE IF NOT EXISTS Atributo (id MEDIUMINT NOT NULL AUTO_INCREMENT, name VARCHAR(255), description VARCHAR(255), type INTEGER, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS Valor  (id MEDIUMINT NOT NULL AUTO_INCREMENT, attrb_id MEDIUMINT NOT NULL, value VARCHAR(255), PRIMARY KEY(id), FOREIGN KEY attrb_ref(attrb_id) REFERENCES Atributo(id)); 
CREATE TABLE IF NOT EXISTS Template (id MEDIUMINT NOT NULL AUTO_INCREMENT, name VARCHAR(255),   PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS Relatorio (id MEDIUMINT NOT NULL AUTO_INCREMENT, attrb_id MEDIUMINT NOT NULL, template_id MEDIUMINT NOT NULL, PRIMARY KEY(id), FOREIGN KEY (attrb_id) REFERENCES Atributo(id), FOREIGN KEY template_ref(template_id) REFERENCES Template(id));