version: 'version'
services: 
  db:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=Abc12345
      - MYSQL_DATABASE=relat_dinamico
    networks:
      - backend
  api:
    build: 
      context: .
    ports:
      - "8080:8080"
    networks:
      - backend


